apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamutkart-deployment
  labels:
    app: gamutkat-app
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: gamutkart-app
  template:
    metadata:
      labels:
        app: gamutkart-app
    spec: 
      containers:
        - name: gamutkart-servicr
          image: nageshvkn/gamutkart-img
          ports:
          - containerPort: 8080
          command: ["/bin/sh"] 
          args: ["-c", "/root/apache-tomcat-8.5.38/bin/startup.sh; while true; do sleep 1; done;"]
