apiVersion: v1
kind: Service
metadata: 
  name: google-service
  labels:
    app: google-app
spec:
  selector:
    app: google-app
  type: NodePort
  ports:
  - nodePort: 31000
    port: 80
    targetPort: 80
